### ISSUE TITLE
Is the API unavailable

### ISSUE THREAD

**Issue by fishbone59** [cryptonthat/nftDownloader#1]
![1656645471410](https://user-images.githubusercontent.com/49779389/176816735-fa14f4f1-7375-486b-8a64-476e5e35fee6.png)
I got an error like this

**Comment by xmattt** [comment]
ETIMEDOUT, means that the api we are calling didn't respond in time. If you encountered this error after successfully downloading a few NFTs then the API is rate limiting your IP.

To resolve:
Locate the delayTime variable, increase this by 500 each time until the error is resolved
